//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoFinal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BD_PROYECTO_FINALEntities1 : DbContext
    {
        public BD_PROYECTO_FINALEntities1()
            : base("name=BD_PROYECTO_FINALEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CATEGORIA> CATEGORIA { get; set; }
        public virtual DbSet<CLIENTE> CLIENTE { get; set; }
        public virtual DbSet<PEDIDO> PEDIDO { get; set; }
        public virtual DbSet<PRODUCTO> PRODUCTO { get; set; }
        public virtual DbSet<SESION> SESION { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
    
        public virtual int REGISTRAR_USER(string uSUARIO, string cLAVE)
        {
            var uSUARIOParameter = uSUARIO != null ?
                new ObjectParameter("USUARIO", uSUARIO) :
                new ObjectParameter("USUARIO", typeof(string));
    
            var cLAVEParameter = cLAVE != null ?
                new ObjectParameter("CLAVE", cLAVE) :
                new ObjectParameter("CLAVE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("REGISTRAR_USER", uSUARIOParameter, cLAVEParameter);
        }
    
        public virtual int USP_PUBLICAR_USER(string nOMBRE_USUARIO, string aPELLIDO_USUARIO, string tELEFONO, string cELULAR, string cORREO, string pAIS, Nullable<int> fK_SESION)
        {
            var nOMBRE_USUARIOParameter = nOMBRE_USUARIO != null ?
                new ObjectParameter("NOMBRE_USUARIO", nOMBRE_USUARIO) :
                new ObjectParameter("NOMBRE_USUARIO", typeof(string));
    
            var aPELLIDO_USUARIOParameter = aPELLIDO_USUARIO != null ?
                new ObjectParameter("APELLIDO_USUARIO", aPELLIDO_USUARIO) :
                new ObjectParameter("APELLIDO_USUARIO", typeof(string));
    
            var tELEFONOParameter = tELEFONO != null ?
                new ObjectParameter("TELEFONO", tELEFONO) :
                new ObjectParameter("TELEFONO", typeof(string));
    
            var cELULARParameter = cELULAR != null ?
                new ObjectParameter("CELULAR", cELULAR) :
                new ObjectParameter("CELULAR", typeof(string));
    
            var cORREOParameter = cORREO != null ?
                new ObjectParameter("CORREO", cORREO) :
                new ObjectParameter("CORREO", typeof(string));
    
            var pAISParameter = pAIS != null ?
                new ObjectParameter("PAIS", pAIS) :
                new ObjectParameter("PAIS", typeof(string));
    
            var fK_SESIONParameter = fK_SESION.HasValue ?
                new ObjectParameter("FK_SESION", fK_SESION) :
                new ObjectParameter("FK_SESION", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("USP_PUBLICAR_USER", nOMBRE_USUARIOParameter, aPELLIDO_USUARIOParameter, tELEFONOParameter, cELULARParameter, cORREOParameter, pAISParameter, fK_SESIONParameter);
        }
    }
}
